# image will be published to ghcr.io/<user>/<name>
name: custom-silverblue
# description will be included in the image's metadata
description: My own take on Fedora Silverblue, with some hardening, some QoL and some debloating

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: packages-install.yml
  - from-file: packages-remove.yml
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        
  - type: gschema-overrides
    include:
      - zz1-QoL-overrides.gschema.override

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.gnome.TextEditor
          - org.gnome.Loupe
          - org.gnome.Papers
          - org.gnome.Calculator
          - org.gnome.SimpleScan
          - org.gnome.font-viewer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
