# image will be published to ghcr.io/<user>/<name>
name: custom-silverblue
# description will be included in the image's metadata
description: My own take on Fedora Silverblue, with some hardening, some QoL and some debloating

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: packages-install.yml
  - from-file: packages-remove.yml
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        
  - type: gschema-overrides
    include:
      - zz1-QoL-overrides.gschema.override

  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      # Minimal flatpak packages: a text editor, an image viewer, a PDF viewer, a calculator, a document scanner, a font viewer, a console
      install:
        - org.gnome.TextEditor
        - org.gnome.Loupe
        - org.gnome.Papers
        - org.gnome.Calculator
        - org.gnome.SimpleScan
        - org.gnome.font-viewer
        - app.devsuite.Ptyxis

  - type: yafti # Install and setup Yafti and its dependencies

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
