type: rpm-ostree
install:
  - gnome-console
  - fastfetch
  - xwininfo # used to easily check which application is running on wayland or not
  - fish
  - lsd
  - bat
  - baobab
  - tldr
  - slirp4netns # used for networking with podman containers 
  - wireshark