type: rpm-ostree
install:
  - gnome-console
  - ufw
  - neofetch
  - fish

remove: 
  - openssh-server
  - firefox
  - firefox-langpacks
  # - virtualbox-guest-additions
  - yelp
  - httpd
  - httpd-core
  - mod_lua
  - mod_http2
  - mod_dnssd
  - libvncserver
  # - perl
  - toolbox
  - qt5-qtbase
  - qt5-qtbase-common
  - qt-settings
  - qt5-qtxmlpatterns

  - gnome-tweaks
  - gnome-tour
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-user-share
  - gnome-remote-desktop
  - gnome-classic-session
  - gnome-shell-extension-window-list
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-common